### ISSUE TITLE
Packages not marked for deletion when release candidates are present

### ISSUE THREAD

**Issue by MathMagique** [blue-yonder/devpi-cleaner#4]
Some packages remain on devpi after deletion with devpi-cleaner option `--dev-only`:

```
package-0.3.0-py2-none-any.whl                              *
package-0.3.0rc5-py2-none-any.whl                           *
package-0.3.0rc4-py2-none-any.whl                           *
package-0.3.0rc3-py2-none-any.whl                           * 
package-0.3.0rc2-py2-none-any.whl                           *
package-0.3.0.post0.dev22_g9e585fb-py2-none-any.whl
package-0.3.0.post0.dev21_g369b980-py2-none-any.whl
```

I have marked the packages I would expect to stay with an asterisk. The last two packages are not deleted. Maybe devpi-cleaner is confused by the absence of a package in version `0.3.0rc1`?

**Comment by theMarix** [comment]
I can't reproduce this issue. @MathMagique, did you specify any additional restrictions? Did you restrict the version? I assume the packages were not even listed for deletion and not only skipped during execution.

**Comment by StephanErb** [comment]
I cannot reproduce either.
