### ISSUE TITLE
Index-specific deletion

### ISSUE THREAD

**Issue by StephanErb** [blue-yonder/devpi-cleaner#8]
Currently, devpi-cleaner wants to remove packages from all available indices of a user. This is a rather specific use case. Instead, it should be possible to specify the indices to clean (or just declare --all).

**Comment by theMarix** [comment]
Do you have any Syntax in mind for the user to express his request? I have thought about this and will post my thoughts here to get some feedback before implementation.

The current syntax for deletion from all indices of a user is this:

```
devpi-cleaner server user package_specification
```

The most straighforward expansion would give

```
devpi-cleaner --all server user package_specification  # delete from all indices
devpi-cleaner server user index package_specification  # delete from a specific index
```

However, this causes a lot of hassle with argument parsing, as the position of the `package_specification` now changes. Thus, I would suggest to use on of the following solutions that both don't require a `--all` flag for the legacy case.

```
devpi-cleaner server user package_specification           # delete from all indices
devpi-cleaner server user/index package_specification  # delete from a specific index
```

This approach very directly maps to the arguments used for `devpi use`. In addition, it does not break with the current syntax.

An even more radical approach would be the following:

```
devpi-cleaner server/user package_specification           # delete from all indices
devpi-cleaner server/user/index package_specification  # delete from a specific index
```

This breaks with the current syntax, but would also open the way to specifying a removal from the whole server – by not even specifying a user.

I tend towards implementing the `devpi-cleaner server user/index package_specification` as it feels most intuitive to me. What do you think?
